openapi: 3.0.1
info:
  title: TODO Plugin
  description: A plugin that allows the user to create and manage a TODO list using ChatGPT. If you do not know the user's username, ask them first before making queries to the plugin. Otherwise, use the username "global".
  version: 'v1'
servers:
  - url: http://10.24.23.38:8003
paths:
  /todos/{username}:
    get:
      operationId: getTodos
      summary: 获取用户的待办列表
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: 用户的名字
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTodosResponse'
    post:
      operationId: addTodo
      summary: 增加一条待办
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: 用户的名字
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addTodoRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  errCode:
                    type: integer
                    description: 插件响应的业务错误码
                  errMsg:
                    type: string
                    description: 插件响应的业务错误信息
                  actionName:
                    type: string
                    description: 执行动作名称
                  actionContent:
                    type: string
                    description: 执行动作内容
                  prompt:
                    type: string
                    description: 用户自定义prompt


    delete:
      operationId: deleteTodo
      summary: 删除一条待办
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: 用户名
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteTodoRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  errCode:
                    type: integer
                    description: 插件响应的业务错误码
                  errMsg:
                    type: string
                    description: 插件响应的业务错误信息
                  actionName:
                    type: string
                    description: 执行动作名称
                  actionContent:
                    type: string
                    description: 执行动作内容
                  prompt:
                    type: string
                    description: 用户自定义prompt

components:
  schemas:
    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: 用户的待办列表
        errCode:
          type: integer
          description: 插件响应的业务错误码
        errMsg:
          type: string
          description: 插件响应的业务错误信息
        actionName:
          type: string
          description: 执行动作名称
        actionContent:
          type: string
          description: 执行动作内容
        prompt:
          type: string
          description: 用户自定义prompt
    addTodoRequest:
      type: object
      required:
        - todo
      properties:
        todo:
          type: string
          description: 需要添加到待办列表的todo
    deleteTodoRequest:
      type: object
      required:
        - todo_idx
      properties:
        todo_idx:
          type: integer
          description: 需要删除的待办的标号